### PR TITLE
Blueprints page UI refinements

### LINKED ISSUE #255: I'm offered to export, even though there is nothing to export
### Description of problem
Similar to issue #254. I'm offered to Export the image, even though it's empty and there is nothing to export.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Go to the overview page
2. Hit the kebab menu
3. Hit **Export**
4. There is nothing to export

### Actual results

The **Export** menu item is active

### Expected results

The **Export** menu item is inactive

### Additional info

screenshot from 2018-06-28 13-07-21

screenshot from 2018-06-28 13-05-57

### LINKED ISSUE #258: upon reload, the "no blueprints" curtain will show for a short second
### Description of problem
This is mostly polish, but I thought it's best to report it before I forget.
If reload the UI, I will see the message that there are no blueprints for a second before the system realizes that "oh, there is some blueprints here actually".
It creates a bit of a jarring experience.

[Screencast of the problem](https://andreasn.portknox.net/s/8qN2wBc8J3yZaqF)

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Shift+reload the overview page in the browser

### Actual results

The UI blinks for a moment, showing the screen that says there are no blueprints.

### Expected results

For it to not do that. Maybe showing a spinner instead.

### LINKED ISSUE #263: lack of error handling
### Description of problem
No errors are handled or reported in the Web UI. Cases where an error state could display are:

- fetching blueprints on the Blueprints page (addressed in PR #268)
- fetching blueprint contents on the Blueprint page > Selected Components tab and Edit Blueprint page (addressed in PR #268)
- fetching available components
- fetching images

### PR DESCRIPTION
**Pull request by jgiardino**
The updates included in this PR:

- Refactor the state for `blueprints` to include:
  - fetchingBlueprints to indicate when blueprints are being fetched, so that we can display a Loading message on the Blueprints page while this is happening (closes #258)
  - errorState for fetching blueprints, so that we can display an error message on the Blueprints page
  - errorState for fetching blueprint contents, so that we can display an error message on the Blueprint page > Selected Components tab or Edit Blueprint page
- Display a loading message when fetching blueprint contents
- Update loading component so that it doesn't display immediately
- On Blueprints page, disable actions Create Image and Export when a blueprint has no contents (closes #255)
- On Blueprints page, disable Create Blueprint action if an error occurred fetching blueprints

Updates not covered in this PR:
- Refactoring the Available Components panel to show loading and error states (noted in issue #249)
- Refactoring Blueprint page > Images tab to show loading and error states (noted in issue #280)
- On Blueprint page > Images tab, disable action Create Image in the Empty State message  (noted in issue #280)

### CODE REVIEW

File: pages/blueprint/index.js [hunk 1]
```diff
@@ -446,6 +453,7 @@ const makeMapStateToProps = () => {
       componentsSortKey: state.sort.components.key,
       componentsSortValue: state.sort.components.value,
       componentsFilters: state.filter.components,
+      blueprintContentsError: {},
```
Comment (jgiardino) [inline pages/blueprint/index.js]: @jkozol I wasn't sure what I should put here. The initial state is null for `blueprints.errorState` and if it's anything but null, it will display an error message where the blueprint contents should display. I think setting this property to `{}` is the right behavior for this case, but would like your input here.

Comment (jkozol) [reply pages/blueprint/index.js]: That seems like it should work for an empty error state. Are you opposed to initializing the errorState to an empty object as well? If we have the default being an empty object I feel like the initial state should be an empty object too. I'm not really sure what the standard should be though so I'm fine either way.

**Comment by jkozol** [comment]
This looks pretty good to me. The only issues I have are one of the create image buttons isn't disabled.



Also, I wasn't able to get the loading message when fetching blueprint contents to display. What is the workflow that shows this? Below is what I see on load:

**Comment by henrywang** [comment]
@jgiardino, could you please rebase master to make end to end test work. Thanks.

**Comment by jgiardino** [comment]
Thanks for reviewing, @jkozol!

> This looks pretty good to me. The only issues I have are one of the create image buttons isn't disabled.

I captured this issue in #280. 

> Also, I wasn't able to get the loading message when fetching blueprint contents to display. What is the workflow that shows this? Below is what I see on load:

I added a 1/2 second delay on displaying the Loading component. Maybe that's what you're seeing?

File: pages/blueprint/index.js (hunk 1 above)
Comment (jgiardino) [reply pages/blueprint/index.js]: Can you clarify what's happening for this set of MapStateToProps?

Currently, the error state displays if anything except `null` is defined. I'm making an assumption that if `if (getBlueprintById(state, props.route.params.blueprint.replace(/\s/g, '-')) !== undefined)` does resolve to undefined, then triggering the error state would be the right thing to do, hence setting it to `{}`, but I could be misinterpreting something here.

For the actual api call, if an error is returned, do you know if we get something back besides just `{}`? Is there a reliable way to test error handling?

**Comment by jgiardino** [comment]
@henrywang Thanks for the tip 👍 I rebased this PR.

**Comment by jgiardino** [comment]
@henrywang issues 2. and 3. should have been fixed with #231 

For issue 1. that you noted, maybe there's some other issue with your local build that's preventing it from fetching the available components? I'm not seeing an issue with my vm and my local build from this branch.

**Comment by henrywang** [comment]
@jkozol, I'll merge this PR if you do not have other comment. Thanks.

File: pages/blueprint/index.js (hunk 1 above)
Comment (jkozol) [reply pages/blueprint/index.js]: Okay. That makes sense to me. I haven't tested for error handling yet so I'm unsure.
